name: CI

on:
  - workflow_dispatch
  - push

jobs:
    build:
      runs-on: macos-latest
  
      steps:
        - name: Clone Sources
          uses: actions/checkout@v4
        - name: Build (RELEASE)
          run : |
            xcodebuild install -target corecrypto_user DSTROOT=$PWD/dst
            xcodebuild install -target corecrypto_kernel DSTROOT=$PWD/dst
            xcodebuild install -target corecrypto_static DSTROOT=$PWD/dst
        - name: Package (RELEASE)
          run : |
            cd dst
            tar -cvf "corecrypto.tar.xz" .
            cd ../
        - name: Upload Artifact (RELEASE)
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: corecrypto
            path: /Users/runner/work/corecrypto/corecrypto/dst/corecrypto.tar.xz
        - name: Build (DEBUG)
          run : |
            xcodebuild install -configuration Debug -target corecrypto_user DSTROOT=$PWD/dbgdst
            xcodebuild install -configuration Debug -target corecrypto_kernel DSTROOT=$PWD/dbgdst
            xcodebuild install -configuration Debug -target corecrypto_static DSTROOT=$PWD/dbgdst
        - name: Package (DEBUG)
          run : |
            cd dbgdst
            tar -cvf "corecrypto_debug.tar.xz" .
            cd ../
        - name: Upload Artifact (DEBUG)
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: corecrypto_debug
            path: /Users/runner/work/corecrypto/corecrypto/dbgdst/corecrypto_debug.tar.xz
